### ISSUE TITLE
Concrete blocks are not implemented 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#1]
Hello 
When I have concrete in my map the server crashes for :

 ErrorException: "Undefined array key "white_concrete"" (EXCEPTION) in "/home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils" at line 201
--- Stack trace ---
  #0 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(201): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[36] Undefined array key "white_concrete", string[100] phar:///home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/ut, int 201)
  #1 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(154): Hebbinkpro\PocketMap\utils\TextureUtils::getBlockTexture(object pocketmine\block\Concrete#84218, object Hebbinkpro\PocketMap\utils\ResourcePack#10895)
  #2 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(116): Hebbinkpro\PocketMap\utils\TextureUtils::createBlockTexture(object pocketmine\block\Concrete#84218, object pocketmine\world\biome\PlainBiome#151618, object Hebbinkpro\PocketMap\utils\ResourcePack#10895)
  #3 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(94): Hebbinkpro\PocketMap\utils\TextureUtils::createCompressedBlockTexture(object pocketmine\block\Concrete#84218, object pocketmine\world\biome\PlainBiome#151618, object Hebbinkpro\PocketMap\utils\ResourcePack#10895, int 2)
  #4 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(135): Hebbinkpro\PocketMap\utils\TextureUtils::createChunkTexture(object pocketmine\world\format\Chunk#105010, object Hebbinkpro\PocketMap\utils\ResourcePack#10895, int 16, int 2)
  #5 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(103): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->drawChunks(object Hebbinkpro\PocketMap\render\PartialRegion#10886, object GdImage#10893)
  #6 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(80): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->renderFull(object Hebbinkpro\PocketMap\render\PartialRegion#10886)
  #7 /home/container/plugins/PocketMap_dev-18.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(61): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->renderPartial(object Hebbinkpro\PocketMap\render\PartialRegion#10886)
  #8 pmsrc/src/scheduler/AsyncTask(84): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->onRun()
  #9 (): pocketmine\scheduler\AsyncTask->run()
--- End of exception information ---
[07:36:50.348] [Server thread/CRITICAL]: RuntimeException: "Worker 1 crashed while running task Hebbinkpro\PocketMap\task\AsyncRegionRenderTask#4940173" (EXCEPTION) in "pmsrc/src/scheduler/AsyncPool" at line 223
--- Stack trace ---
  #0 pmsrc/src/scheduler/AsyncPool(260): pocketmine\scheduler\AsyncPool->checkCrashedWorker(int 1, object Hebbinkpro\PocketMap\task\AsyncRegionRenderTask#4940173)
  #1 pmsrc/src/scheduler/AsyncPool(235): pocketmine\scheduler\AsyncPool->collectTasksFromWorker(int 1)
  #2 pmsrc/src/Server(1786): pocketmine\scheduler\AsyncPool->collectTasks()
  #3 pmsrc/src/Server(1671): pocketmine\Server->tick()
  #4 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #5 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(357): pocketmine\server()
  #7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

Thank you
Rover17

**Comment by Hebbinkpro** [comment]
Hi, thanks for addressing this issue. It seems that concrete is implemented the same as logs, stones, leaves, etc. in the mc resource packs but I forgot to implement concrete in my code. It is possible that this issue can occur for other block types as well.

I will fix this issue asap when I have the time.

**Comment by Hebbinkpro** [comment]
Fixed in v0.2.3
