### ISSUE TITLE
Webserver crashes when trying to acces with https

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#11]
Hello
The Web server crashes when trying to access with https, but the server doesn't crash just this error appear and the website cannot be accessed before a server restart.

[CRITICAL] Undefined array key "Host"
#0 phar:///home/container/plugins/PocketMap_dev-27.phar/src/Hebbinkpro/PocketMap/libs/Hebbinkpro/WebServer/http/header/HttpHeaders.php(41): pocketmine\errorhandler\ErrorToExceptionHandler::handle(2, 'Undefined array...', 'phar:///home/co...', 41)
#1 phar:///home/container/plugins/PocketMap_dev-27.phar/src/Hebbinkpro/PocketMap/libs/Hebbinkpro/WebServer/http/HttpRequest.php(54): Hebbinkpro\PocketMap\libs\Hebbinkpro\WebServer\http\header\HttpHeaders->get('Host')
#2 phar:///home/container/plugins/PocketMap_dev-27.phar/src/Hebbinkpro/PocketMap/libs/Hebbinkpro/WebServer/HttpServer.php(113): Hebbinkpro\PocketMap\libs\Hebbinkpro\WebServer\http\HttpRequest::fromString('GET / HTTP/1.1\r...')
#3 phar:///home/container/plugins/PocketMap_dev-27.phar/src/Hebbinkpro/PocketMap/libs/Hebbinkpro/WebServer/HttpServer.php(60): Hebbinkpro\PocketMap\libs\Hebbinkpro\WebServer\HttpServer->serveExistingConnections()
#4 phar:///home/container/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(109): Hebbinkpro\PocketMap\libs\Hebbinkpro\WebServer\HttpServer->onRun()
#5 [internal function]: pocketmine\thread\Thread->run()

**Comment by Hebbinkpro** [comment]
It's a HTTP server and not an HTTPS server, so only `http://` will work and `https://` will not.
But its not great that the web server crashes when someone tries to access it using `https`

**Comment by Rover17-Dev** [comment]
Yes I know but it would be great if it didn't crash

**Comment by Hebbinkpro** [comment]
The crash should be fixed now
