### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NdaruAjaa** [Hebbinkpro/PocketMap#12]
How do I connect to the web?

**Comment by Hebbinkpro** [comment]
You can connect to the webserver by going to `http://<server_ip>:<web_server_port>/`.
You can set the web server port in the `config.yml`.

The default port is set to `3000`, but this port will probably not work.
For a Pterodactyl panel, you can allocate an extra port to your server and replace the  `port` in the config with the port you got allocated.

**Comment by NdaruAjaa** [comment]
Does the <server_ip> part have to be a number?

**Comment by Hebbinkpro** [comment]
It's the same address as you use for the Minecraft server, so it can be a number like `127.0.0.1` but it can also be something like `play.server.net` or whatever the address of your server is

**Comment by NdaruAjaa** [comment]
Ok thank you
