### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by ant253** [Hebbinkpro/PocketMap#13]
Hi, this seems like a very good plugin for my earth smp however what ports do i need to port forward (im running the server on an ubuntu oracle cloud server).

Thank you

**Comment by Hebbinkpro** [comment]
Hi, it does not matter which port you use.
But don't forget to set the right port in the config.yml

**Comment by AnTx253** [comment]
@Hebbinkpro Thanks for replying so quick, Im probably just going to use port 3000 (also this is public on the web right?)

Thanks
