### ISSUE TITLE
Compatible Plugins?

### ISSUE THREAD

**Issue by ant253** [Hebbinkpro/PocketMap#14]
Hi sorry for the bobardment of questions, however have you made any or is there any pocketmine plugins like towny which has towns show up on the map, if not is there a factions/towns/nations plugin in general you recommend (It doesnt have to show up on pocketmap) ?

**Comment by Hebbinkpro** [comment]
The plugin does not support markers and areas at the moment. This will maybe be added in the future. The only plugin that is currently supported is Customies, this is a plugin to add custom blocks/items to a pmmp server.

I haven't used any factions plugin before, so I cannot recommend anything. But you can probably find such a plugin at [Poggit](https://poggit.pmmp.io/).
