### ISSUE TITLE
Crash after latest pocketmine update

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#15]
Hello, 
The plugin is currently crashing after latest pocketmine update

[06:51:20.354] [Server thread/CRITICAL]: Error: "Undefined constant pocketmine\data\bedrock\block\BlockTypeNames::CONCRETE_POWDER" (EXCEPTION) in "plugins/PocketMap_dev-31.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils" at line 237
--- Stack trace ---
  #0 plugins/PocketMap_dev-31.phar/src/Hebbinkpro/PocketMap/textures/TerrainTexturesOptions(20): Hebbinkpro\PocketMap\utils\TextureUtils::getBlockTextureName(object pocketmine\block\Bedrock#41733)
  #1 plugins/PocketMap_dev-31.phar/src/Hebbinkpro/PocketMap/PocketMap(273): Hebbinkpro\PocketMap\textures\TerrainTexturesOptions->__construct(object pocketmine\block\Bedrock#41733, int 0, int 3)
  #2 plugins/PocketMap_dev-31.phar/src/Hebbinkpro/PocketMap/PocketMap(175): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()
  #3 pmsrc/src/plugin/PluginBase(119): Hebbinkpro\PocketMap\PocketMap->onEnable()
  #4 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#42057)
  #6 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41730)
  #7 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #8 pmsrc/src/PocketMine(357): pocketmine\server()
  #9 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
  
  Thank you

**Comment by Hebbinkpro** [comment]
Fixed in v0.4.0.

**Comment by Rover17-Dev** [comment]
[17:26:50.356] [Server thread/CRITICAL]: ErrorException: "Undefined array key "textures"" (EXCEPTION) in "plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures" at line 84
--- Stack trace ---
  #0 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures(84): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[30] Undefined array key "textures", string[106] phar:///home/container/plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/te, int 84)
  #1 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures(68): Hebbinkpro\PocketMap\textures\TerrainTextures->loadFromFile()
  #2 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures(43): Hebbinkpro\PocketMap\textures\TerrainTextures::fromExistingTextures(string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\textures\TerrainTexturesOptions#41884)
  #3 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/PocketMap(281): Hebbinkpro\PocketMap\textures\TerrainTextures::generate(object Hebbinkpro\PocketMap\PocketMap#42261, string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\textures\TerrainTexturesOptions#41884)
  #4 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/PocketMap(235): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()
  #5 pmsrc/src/plugin/PluginBase(119): Hebbinkpro\PocketMap\PocketMap->onEnable()
  #6 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #7 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#42261)
  #8 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41730)
  #9 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #10 pmsrc/src/PocketMine(357): pocketmine\server()
  #11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
