### ISSUE TITLE
Crash after latest update

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#16]
[17:26:50.356] [Server thread/CRITICAL]: ErrorException: "Undefined array key "textures"" (EXCEPTION) in "plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures" at line 84
--- Stack trace ---
  #0 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures(84): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[30] Undefined array key "textures", string[106] phar:///home/container/plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/te, int 84)
  #1 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures(68): Hebbinkpro\PocketMap\textures\TerrainTextures->loadFromFile()
  #2 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/textures/TerrainTextures(43): Hebbinkpro\PocketMap\textures\TerrainTextures::fromExistingTextures(string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\textures\TerrainTexturesOptions#41884)
  #3 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/PocketMap(281): Hebbinkpro\PocketMap\textures\TerrainTextures::generate(object Hebbinkpro\PocketMap\PocketMap#42261, string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\textures\TerrainTexturesOptions#41884)
  #4 plugins/PocketMap_dev-34.phar/src/Hebbinkpro/PocketMap/PocketMap(235): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()
  #5 pmsrc/src/plugin/PluginBase(119): Hebbinkpro\PocketMap\PocketMap->onEnable()
  #6 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #7 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#42261)
  #8 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41730)
  #9 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #10 pmsrc/src/PocketMine(357): pocketmine\server()
  #11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Hebbinkpro** [comment]
I think this is an issue with the new resource pack system. If you remove the `resource_packs` folder in the plugin data of PocketMap it should be fixed!

**Comment by Hebbinkpro** [comment]
Fixed
