### ISSUE TITLE
Block texture does not exist

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#18]
TypeError: "imagecopy(): Argument #2 ($src_image) must be of type GdImage, null given" (EXCEPTION) in "/home/container/plugins/PocketMap_dev-38.phar/src/Hebbinkpro/PocketMap/render/AsyncChunkRenderTask" at line 135
--- Stack trace ---
  #0 /home/container/plugins/PocketMap_dev-38.phar/src/Hebbinkpro/PocketMap/render/AsyncChunkRenderTask(135): imagecopy(object GdImage#121521, null, int 0, int 0, int 0, int 0, int 16, int 16)
  #1 /home/container/plugins/PocketMap_dev-38.phar/src/Hebbinkpro/PocketMap/render/AsyncChunkRenderTask(71): Hebbinkpro\PocketMap\render\AsyncChunkRenderTask->createChunkTexture(object pocketmine\world\format\Chunk#121731, object Hebbinkpro\PocketMap\textures\TerrainTextures#17, int 16, int 16)
  #2 /home/container/plugins/PocketMap_dev-38.phar/src/Hebbinkpro/PocketMap/render/AsyncRenderTask(49): Hebbinkpro\PocketMap\render\AsyncChunkRenderTask->render(object Hebbinkpro\PocketMap\region\PartialRegion#11011, object GdImage#11015)
  #3 pmsrc/src/scheduler/AsyncTask(82): Hebbinkpro\PocketMap\render\AsyncRenderTask->onRun()
  #4 (): pocketmine\scheduler\AsyncTask->run()
--- End of exception information ---
[15:11:37.102] [Server thread/CRITICAL]: pocketmine\thread\ThreadCrashException: "Worker 3 crashed while running task Hebbinkpro\PocketMap\render\AsyncChunkRenderTask#777466" (EXCEPTION) in "pmsrc/src/scheduler/AsyncPool" at line 226
--- Stack trace ---
  #0 pmsrc/src/scheduler/AsyncPool(266): pocketmine\scheduler\AsyncPool->checkCrashedWorker(int 3, object Hebbinkpro\PocketMap\render\AsyncChunkRenderTask#777466)
  #1 pmsrc/src/scheduler/AsyncPool(241): pocketmine\scheduler\AsyncPool->collectTasksFromWorker(int 3)
  #2 pmsrc/src/Server(1793): pocketmine\scheduler\AsyncPool->collectTasks()
  #3 pmsrc/src/Server(1678): pocketmine\Server->tick()
  #4 pmsrc/src/Server(1064): pocketmine\Server->tickProcessor()
  #5 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(357): pocketmine\server()
  #7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[15:11:37.102] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed.

**Comment by Hebbinkpro** [comment]
Hi, thanks for reporting the issue. It seams that the texture of a block cannot be found, and I don't know why, maybe an issue with a resource pack?
I have released a fix, but this will only prevent the server from crashing, so it can happen that your map now contains a few black spots where blocks should be.
