### ISSUE TITLE
Concrete colors no longer loading correctly 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#19]
Hello
Concrete blocks colors are not longer loading correctly neither the barrier blocks 
Thank you for your plugin

**Comment by Hebbinkpro** [comment]
Hi, what do you mean with the concrete colors not loading correctly? Is the color wrong or are they not loading at all (black spots)?

For the barriers, I've currently added a system that will hide all "hidden" blocks, including barriers don't render. But I can add a setting in the config for this.

**Comment by Rover17-Dev** [comment]
![image](https://github.com/Hebbinkpro/PocketMap/assets/74236531/fc25352d-77e1-4a54-bd80-ee909e3c655b)
I mean that there are a lot of concrete colors in my map, and it all render as white concrete 

and here it is all rendering as black concrete, but there is also white and gray in the map
![image](https://github.com/Hebbinkpro/PocketMap/assets/74236531/c8773d42-d792-4fce-9606-19c9793bc081)

**Comment by Rover17-Dev** [comment]
It is happening after the latest updates

**Comment by Hebbinkpro** [comment]
Hey, thanks for providing the screenshots.
It looks like there is only one concrete color per chunk, this will probably also be the case for concrete powder and wool.

**Comment by Hebbinkpro** [comment]
Fixed in v0.4.4
