### ISSUE TITLE
Other files in worlds folder causes the server to crash 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#2]
Fixed first issue

---
PocketMap cannot register custom blocks
I now this issue is not fixable but it would be great if I could use it with Customies

**Comment by Hebbinkpro** [comment]
It seems that you have a file or folder in the `worlds` directory of your server that isn't a world.

You can fix it by removing everything except the worlds in the `worlds` folder of your server.

It is still a bug in the plugin so I will fix this in the next release.

**Comment by Hebbinkpro** [comment]
Fixed in v0.2.4
