### ISSUE TITLE
colored window turns into bedrock

### ISSUE THREAD

**Issue by mathchat900** [Hebbinkpro/PocketMap#26]
Hi !,
When I put colored glass on my Minecraft world, the normal glass is transparent but the other colored glass turns into bedrock.

![image](https://github.com/Hebbinkpro/PocketMap/assets/73251064/864868b9-6ae4-4629-8b26-8747d9ed7f71)

![image](https://github.com/Hebbinkpro/PocketMap/assets/73251064/ba7d6c45-a0a1-490c-b93e-61e87d927d75)

thanks and Have a good day

**Comment by Hebbinkpro** [comment]
Moved to issue #25
