### ISSUE TITLE
Support custom blocks 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#3]
Hello
It would be great if the plugin could replace custom blocks by something like dirt block in the world render because actually it is just crashing the server
Like when it see and unknown block id replacing it by dirt or I don't know

Thank you

**Comment by Hebbinkpro** [comment]
The plugin is only tested using vanilla blocks. I will look into this to add a placeholder for non-vanilla blocks. I'm also planning on creating a way to support multiple texture packs.

For now it is possible to add all your custom blocks to the `blocks.json` and `textures/terrain_texture.json` and add the pngs of the textures in `textures/blocks/` in the latest resource pack (v1.20.10.1) in the plugin data.
