### ISSUE TITLE
Problem: SetActorDataPacket.php

### ISSUE THREAD

**Issue by DevPapo** [Hebbinkpro/PocketMap#31]
PocketMine-MP Crash Dump Thu Jul 11 17:07:08 UTC 2024

PocketMine-MP version: 5.17.0 [Protocol 686]
Git commit: 37bf4bc0b0c095758c8ee09e5681a369396da7ce
PHP version: 8.2.17
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN

Thread: Main
Error: CortexPE\Commando\BaseSubCommand::__construct(): Argument #1 ($name) must be of type string, Hebbinkpro\PocketMap\PocketMap given, called in /home/container/plugins/PocketMap-main/src/Hebbinkpro/PocketMap/commands/PocketMapCommand.php on line 50
File: /home/container/virions/Commando-bc68c93d91f0099e1d8ae724e133b42f3dac36cb/src/CortexPE/Commando/BaseSubCommand
Line: 60
Type: TypeError
Backtrace:
#0 plugins/PocketMap-main/src/Hebbinkpro/PocketMap/commands/PocketMapCommand(50): CortexPE\Commando\BaseSubCommand->__construct(object Hebbinkpro\PocketMap\PocketMap#50673, string[4] help, string[26] Get a list of all commands, array[1])
#1 /home/container/virions/Commando-bc68c93d91f0099e1d8ae724e133b42f3dac36cb/src/CortexPE/Commando/BaseCommand(89): Hebbinkpro\PocketMap\commands\PocketMapCommand->prepare()
#2 plugins/PocketMap-main/src/Hebbinkpro/PocketMap/PocketMap(188): CortexPE\Commando\BaseCommand->__construct(object Hebbinkpro\PocketMap\PocketMap#50673, string[9] pocketmap, string[17] PocketMap command, array[1])
#3 pmsrc/src/plugin/PluginBase(119): Hebbinkpro\PocketMap\PocketMap->onEnable()
#4 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#5 pmsrc/src/Server(1404): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#50673)
#6 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#50217)
#7 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#8 pmsrc/src/PocketMine(378): pocketmine\server()
#9 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMP1hBVuH.tar/src/PocketMine.php)

Code:
[51] 	/** @var string[] */
[52] 	private array $permissions = [];
[53] 	/** @var CommandSender */
[54] 	protected CommandSender $currentSender;
[55] 	/** @var BaseCommand */
[56] 	protected BaseCommand $parent;
[57] 	/** @var BaseConstraint[] */
[58] 	private array $constraints = [];
[59] 
[60] 	public function __construct(string $name, string $description = "", array $aliases = []) {
[61] 		$this->name = $name;
[62] 		$this->description = $description;
[63] 		$this->aliases = $aliases;
[64] 
[65] 		$this->prepare();
[66] 
[67] 		$this->usageMessage = $this->generateUsageMessage();
[68] 	}
[69] 
[70] 	abstract public function onRun(CommandSender $sender, string $aliasUsed, array $args): void;

![Screenshot_20240711_132637_Chrome](https://github.com/Hebbinkpro/PocketMap/assets/101963541/b5d2f1b3-72de-404b-9e0c-5c9aafaaa47f)

**Comment by Hebbinkpro** [comment]
Hey, it looks like you are using the wrong version of Commando.
PocketMap uses [Commando v3.1.0 from paroxity](https://github.com/Paroxity/Commando).
It is recommended to use the phar you can download on [Poggit CI](https://poggit.pmmp.io/ci/Hebbinkpro/PocketMap/~) , but if you want to run PocketMap from source I recommend using [Pharynx](https://github.com/SOF3/pharynx), since this will install all the required dependencies.
