### ISSUE TITLE
Cannot render 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#4]
Hello again
Each time I'm trying to do the render of my world, my server crashes for this reason:
Error: pocketmine\world\format\Chunk::getBlockStateId(): Argument #2 ($y) must be of type int, null given, called in phar:///home/container/plugins/PocketMap_dev-22.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils.php on line 83
File: pmsrc/src/world/format/Chunk
Line: 98
Type: TypeError

Thank you for your plugin

**Comment by Hebbinkpro** [comment]
Thanks for reporting all those issues.
I've fixed it.
