### ISSUE TITLE
Custom block are crashing the render

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#5]
Hello again
I'm sorry for making so much issues but my custom block from Customies are crashing the server

BAD PLUGIN: PocketMap

Thread: AsyncWorker#0
Error: No serializer registered for -----\block\Bin with type ID 30014
File: pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer
Line: 252
Type: pocketmine\data\bedrock\block\BlockStateSerializeException
Backtrace:
#0 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/utils/block/BlockStateParser(21): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serializeBlock(object ----\block\Bin#151869)
#1 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(344): Hebbinkpro\PocketMap\utils\block\BlockStateParser::getBlockStateData(object ----\block\Bin#151869)
#2 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(197): Hebbinkpro\PocketMap\utils\TextureUtils::getBlockTextureName(object -----\block\Bin#151869)
#3 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(159): Hebbinkpro\PocketMap\utils\TextureUtils::getBlockTexture(object ----\block\Bin#151869, object Hebbinkpro\PocketMap\utils\ResourcePack#14)
#4 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(120): Hebbinkpro\PocketMap\utils\TextureUtils::createBlockTexture(object ----\block\Bin#151869, object pocketmine\world\biome\PlainBiome#151865, object Hebbinkpro\PocketMap\utils\ResourcePack#14)
#5 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/utils/TextureUtils(98): Hebbinkpro\PocketMap\utils\TextureUtils::createCompressedBlockTexture(object ----\block\Bin#151869, object pocketmine\world\biome\PlainBiome#151865, object Hebbinkpro\PocketMap\utils\ResourcePack#14, int 16)
#6 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(135): Hebbinkpro\PocketMap\utils\TextureUtils::createChunkTexture(object pocketmine\world\format\Chunk#124182, object Hebbinkpro\PocketMap\utils\ResourcePack#14, int 16, int 16)
#7 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(103): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->drawChunks(object Hebbinkpro\PocketMap\render\PartialRegion#15, object GdImage#18)
#8 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(80): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->renderFull(object Hebbinkpro\PocketMap\render\PartialRegion#15)
#9 /home/container/plugins/PocketMap_dev-23.phar/src/Hebbinkpro/PocketMap/task/AsyncRegionRenderTask(61): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->renderPartial(object Hebbinkpro\PocketMap\render\PartialRegion#15)
#10 pmsrc/src/scheduler/AsyncTask(82): Hebbinkpro\PocketMap\task\AsyncRegionRenderTask->onRun()
#11 (): pocketmine\scheduler\AsyncTask->run()

Thank you a lot

**Comment by Hebbinkpro** [comment]
I'm currently working on a larger release which will also include support for Customies and custom resource packs.

I will make a small bug fix release for this issue, but it is possible that another issue will pop up because it is not yet made for other blocks than implemented by PocketMine.

If v0.3.0 releases, those issues should be fixed :D

**Comment by Hebbinkpro** [comment]
I hope all your issues are fixed with the new release. If you encounter more issues, please report them :D
