### ISSUE TITLE
Not all resource packs are supported

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#7]
Hello 
After the latest update, this bug appeared

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PocketMap

Thread: Main
Error: Trying to access array offset on value of type null
File: plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures
Line: 161
Type: ErrorException
Backtrace:
#0 plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(161): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[51] Trying to access array offset on value of type null, string[113] phar:///home/container/plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/te, int 161)
#1 plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(85): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::extractResourcePack(object pocketmine\resourcepacks\ZippedResourcePack#44114, string[53] /home/container/plugin_data/PocketMap/resource_packs/, null)
#2 plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(34): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::extractResourcePacks(string[53] /home/container/plugin_data/PocketMap/resource_packs/, object pocketmine\resourcepacks\ResourcePackManager#41187, null)
#3 plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/PocketMap(281): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::generate(object Hebbinkpro\PocketMap\PocketMap#41907, string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\terrainTextures\TerrainTexturesOptions#42150)
#4 plugins/PocketMap_dev-25.phar/src/Hebbinkpro/PocketMap/PocketMap(177): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()
#5 pmsrc/src/plugin/PluginBase(118): Hebbinkpro\PocketMap\PocketMap->onEnable()
#6 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#7 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#41907)
#8 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41598)
#9 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#10 pmsrc/src/PocketMine(357): pocketmine\server()
#11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Thank you

**Comment by Hebbinkpro** [comment]
This issue is caused because one of your resource packs don't contain a `textures/terrain_texture.json`, and at this point only that file is read for extracting the images from the pack. I will release a fix so that that file isn't required, I just forgot to implement support for packs without that file

**Comment by Rover17-Dev** [comment]
My packs have the textures/terrain_texture.json file. I think it is maybe caused because I have added my customs block in it.

**Comment by Hebbinkpro** [comment]
Custom blocks textures should not be a problem, I've tested that.
I think that the folder structure of the zip is different than expected.

I guess your pack is something like`pack.zip/pack/manifest.json` and a pack will currently only work with `pack.zip/manifest.json`.  This is because the latter one was easier to implement, but they need both to be implemented.

**Comment by Rover17-Dev** [comment]
[10:58:51.437] [Server thread/CRITICAL]: ErrorException: "Undefined array key "texture_data"" (EXCEPTION) in "plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures" at line 250
--- Stack trace ---
  #0 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(250): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[34] Undefined array key "texture_data", string[113] phar:///home/container/plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/te, int 250)
  #1 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(208): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::getResourcePackBlockIndex(string[90] /home/container/plugin_data/PocketMap/resource_packs/31589455-80ba-42e2-a806-102)
  #2 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(36): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::indexBlocks(string[53] /home/container/plugin_data/PocketMap/resource_packs/, array[1], null)
  #3 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/PocketMap(281): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::generate(object Hebbinkpro\PocketMap\PocketMap#42130, string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\terrainTextures\TerrainTexturesOptions#41788)
  #4 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/PocketMap(177): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()
  #5 pmsrc/src/plugin/PluginBase(118): Hebbinkpro\PocketMap\PocketMap->onEnable()
  #6 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #7 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#42130)
  #8 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41606)
  #9 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #10 pmsrc/src/PocketMine(357): pocketmine\server()
  #11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Rover17-Dev** [comment]
Still this happening
