### ISSUE TITLE
Texture packs not supported 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#8]
Hello
 My texture pack is still crashing the server
 
 [10:58:51.437] [Server thread/CRITICAL]: ErrorException: "Undefined array key "texture_data"" (EXCEPTION) in "plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures" at line 250
--- Stack trace ---
#0 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(250): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[34] Undefined array key "texture_data", string[113] phar:///home/container/plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/te, int 250)
https://github.com/Hebbinkpro/PocketMap/issues/1 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(208): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::getResourcePackBlockIndex(string[90] /home/container/plugin_data/PocketMap/resource_packs/31589455-80ba-42e2-a806-102)
https://github.com/Hebbinkpro/PocketMap/issues/2 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/terrainTextures/TerrainTextures(36): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::indexBlocks(string[53] /home/container/plugin_data/PocketMap/resource_packs/, array[1], null)
https://github.com/Hebbinkpro/PocketMap/issues/3 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/PocketMap(281): Hebbinkpro\PocketMap\terrainTextures\TerrainTextures::generate(object Hebbinkpro\PocketMap\PocketMaphttps://github.com/Hebbinkpro/PocketMap/issues/42130, string[53] /home/container/plugin_data/PocketMap/resource_packs/, object Hebbinkpro\PocketMap\terrainTextures\TerrainTexturesOptions#41788)
#4 plugins/PocketMap_dev-26.phar/src/Hebbinkpro/PocketMap/PocketMap(177): Hebbinkpro\PocketMap\PocketMap->loadTerrainTextures()
https://github.com/Hebbinkpro/PocketMap/issues/5 pmsrc/src/plugin/PluginBase(118): Hebbinkpro\PocketMap\PocketMap->onEnable()
https://github.com/Hebbinkpro/PocketMap/issues/6 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
https://github.com/Hebbinkpro/PocketMap/issues/7 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object Hebbinkpro\PocketMap\PocketMap#42130)
#8 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41606)
#9 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#10 pmsrc/src/PocketMine(357): pocketmine\server()
#11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Hebbinkpro** [comment]
This is an issue with the `textures/terrain_texture.json` file in your texture pack. It does not contain `texture_data`, which is required.
